name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with: 
          options: "--line-length 100"
      - uses: chartboost/ruff-action@v1
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort . --check --diff --profile black

