name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE: 0

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: 'harvest-transformer/*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run tests
        run: pytest ./tests -vv
